# nutrients not listed in dict are assumed to be 0
# units are diy.soylent.me units for each nutrient
# serving_size is in grams
ingredients = [
        {
            'name' : 'masa harina',
            'serving_size' : 100,
            'kcal' : 365,
            'carbohydrates' : 76.29,
            'protein' : 9.3,
            'total_fat' : 3.86,
            'omega3' : 0.052,
            'omega6' : 1.672,
            'fiber' : 6.7,
            'calcium' : 0.141,
            'copper' : 0.18,
            'iron' : 7.2,
            'magnesium' : 110,
            'manganese' : 0.5,
            'phosphorus' : 0.223,
            'potassium' : 0.298,
            'selenium' : 14,
            'sodium' : 0.03,
            'sulfur' : 0.364,
            'zinc' : 1.8,
            'vitamin_a' : 1000,
            'vitamin_b6' : 0.475,
            'vitamin_k' : 0.3,
            'thiamin' : 1.4,
            'riboflavin' : 0.097,
            'folate' : 29,
            'pantothenic_acid' : 0.7,
            'choline' : 8.6,
            },
        {
            'name' : 'NOW Foods Calcium and Magnesium',
            'serving_size' : 4.5,
            'calcium' : .4,
            'magnesium' : 400,
            'vitamin_d' : 200,
            },
        {
            'name' : 'Potassium Citrate',
            'serving_size' : .275,
            'potassium' : 0.099,
            },
        {
            'name' : 'Iodised Salt',
            'serving_size' : 2,
            'chloride' : 1.2,
            'iodine' : 94,
            'sodium' : 0.8,
            },
        {
                'name' : 'Choline Bitartrate',
                'serving_size' : 1,
                'choline' : 410,
                },
        {
                'name' : 'Soybean Oil',
                'serving_size' : 100,
                'kcal' : 884,
                'calcium' : .4,
                'magnesium' : 400,
                'vitamin_d' : 200,
                },
        {
                'name' : 'Whey Protein Isolate',
                'serving_size' : 28,
                'kcal' : 110,
                'protein' : 25,
                'total_fat' : 0.5,
                'cholesterol' : 5,
                'calcium' : 0.15,
                'potassium' : 0.135,
                'sodium' : 0.045,
                'sulfur' : 0.668,
                },
        {
                'name' : 'GNC Mega Men Sport Vanilla Bean',
                'serving_size' : 36,
                'kcal' : 130,
                'carbohydrates': 15,
                'protein' : 10,
                'total_fat' : 2.5,
                'fiber' : 8,
                'vitamin_a' : 5000,
                'vitamin_b6' : 50,
                'vitam_b12' : 50,
                'vitamin_c' : 300,
                'vitamin_d' : 600,
                'vitamin_e' : 30,
                'vitamin_k' : 80,
                'thiamin' : 50,
                'riboflavin' : 50,
                'niacin' : 50,
                'folate' : 600,
                'pantothenic_acid' : 50,
                'biotin' : 300,
                'choline' : 10,
                'calcium' : 0.2,
                'chloride' : 0.15,
                'chromium' : 120,
                'copper' : 2,
                'iodine' : 150,
                'magnesium' : 50,
                'manganese' : 2,
                'molybdenum' : 75,
                'potassium' : 0.25,
                'selenium' : 200,
                'zinc' : 25,
                },
        ]
